### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by pyoxa**

### CODE REVIEW

**Comment by pyoxa** [comment]
LGTM :rocket:

**Comment by pyoxa** [comment]
@HKozubek any update on this?

**Comment by HubertKozubek** [comment]
Thank you for your time spent trying to improve this package. Sadly I have to close this PR, because it isn't compliant with the [contribution rules](https://github.com/HKozubek/prediction-strength/blob/main/CONTRIBUTING.md). Please read them before trying to resubmit your changes.

**Comment by pyoxa** [comment]
wtf?

**Pull request closed without merging**
